name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }} # Setup Python for each version in the matrix
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make install

    - name: Format code
      run: |
        make format

    - name: Lint code
      run: |
        make lint

    - name: Run tests
      run: |
        make test